on: [issue_comment]

jobs:
  bossbot_issue_comment_cleanup:
    runs-on: ubuntu-latest
    name: BossBot Issues Cleanup
    steps:
      - uses: actions/checkout@v2
      - name: BossBot Issues Cleanup - action step
        uses: jcolls/bossbot-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGEX_TOKEN: (?s)(?<=[XYZC logo]|From).*?(?=2123456)
          SHOW_ANNOTATION: true
